# Generated by Django 5.0.4 on 2024-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composed_at',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
