# Generated by Django 5.0.4 on 2024-05-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_product_composed_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
